FROM node:18.5.0-alpine

WORKDIR /usr/src/app

# instead of copying code (see `docker-compose.yml`)
COPY package*.json ./

# speed up subsequent npm installs
CMD npm config set cache-min 9999999 && \
    npm install && \
    npm run start:dev